import Head from 'next/head';
import Navbar from '../components/navbar/Navbar';
// import { useState } from 'react';
// import Image from 'next/image';
// import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Travel App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<h1>Home Page</h1>
		</div>
	);
}
