import Head from 'next/head';
import { useState } from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// export async function getServerSideProps(context) {
// 	const response = await fetch('http://localhost:3000/api/flights');
// 	const data = await response.json();

// 	return {
// 		props: { data }, // will be passed to the page component as props
// 	};
// }

export default function Home() {
	const [city, setCity] = useState('');
	const [country, setCountry] = useState('');

	const handleSubmit = (e) => {
		e.preventDefault();
		fetch('http://localhost:3000/api/pois', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify({ city, country }),
		})
			.then((res) => res.json())
			.then((data) => console.log(data));
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Travel App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>Making a travel site with Amadeus</h1>
			<h3>
				Find Interesting Spots in: {city}, {country}
			</h3>
			<form onSubmit={handleSubmit}>
				<input
					value={city}
					onChange={(e) => setCity(e.target.value)}
					type="text"
					placeholder="City"
				/>
				<input
					value={country}
					onChange={(e) => setCountry(e.target.value)}
					type="text"
					placeholder="Country"
				/>
				<button>Search</button>
			</form>
		</div>
	);
}
